# crée un nouvel utilisateur et rajoute une clé autorisé pour se logguer
- name: create a new group (non-root)
  group: 
    name: "deployers"
    state: present
  become: true

- name: create a new user (non-root)
  user: 
    name: "deployer"
    group: "deployers"
    shell: "/bin/bash"
    state: present 
  become: true

- name: add authorized_key to non root user
  authorized_key:
    user: deployer
    state: present
    key: "{{lookup('file', '/home/patou/.ssh/introansible.pub') }}"
  become: true
